using DnDGame.Domain.Engine.Dice;

namespace DnDGame.Domain.Engine.Combat;

/// <summary>
/// Immutable input for a deterministic dodge calculation. Dice, when required,
/// must have been generated by the orchestrating flow before this request is made.
/// </summary>
public sealed class DodgeRequest
{
    public DodgeRequest(
        int attackerStat,
        int defenderStat,
        IEnumerable<int>? attackerModifiers = null,
        IEnumerable<int>? defenderModifiers = null,
        DiceResult? diceResult = null)
    {
        AttackerStat = attackerStat;
        DefenderStat = defenderStat;
        AttackerModifiers = (attackerModifiers ?? Array.Empty<int>()).ToArray();
        DefenderModifiers = (defenderModifiers ?? Array.Empty<int>()).ToArray();
        DiceResult = diceResult;
    }

    public int AttackerStat { get; }
    public int DefenderStat { get; }
    public IReadOnlyList<int> AttackerModifiers { get; }
    public IReadOnlyList<int> DefenderModifiers { get; }
    public DiceResult? DiceResult { get; }
}
