using DnDGame.Domain.Engine.Dice;

namespace DnDGame.Domain.Engine.SavingThrows;

/// <summary>
/// Input for a saving throw. The dice result must be generated by the backend
/// through IDiceEngine before this request enters the game flow.
/// </summary>
public sealed class SavingThrowRequest
{
    public SavingThrowRequest(DiceResult diceResult, int difficultyClass, int modifier)
    {
        ArgumentNullException.ThrowIfNull(diceResult);

        DiceResult = diceResult;
        DifficultyClass = difficultyClass;
        Modifier = modifier;
    }

    public DiceResult DiceResult { get; }

    public int DifficultyClass { get; }

    public int Modifier { get; }
}
